export const months = [
    { name: 'January', value: '01' },
    { name: 'February', value: '02' },
    { name: 'March', value: '03' },
    { name: 'April', value: '04' },
    { name: 'May', value: '05' },
    { name: 'June', value: '06' },
    { name: 'July', value: '07' },
    { name: 'August', value: '08' },
    { name: 'September', value: '09' },
    { name: 'October', value: '10' },
    { name: 'November', value: '11' },
    { name: 'December', value: '12' },
  ];

export const pinkShades = [
  "#ffb3c6",
  "#ffccd5",
  "#ffe0e6",
  "#ff99af",
  "#ff6f91",
  "#fcb8c7",
  "#fcdbdf",
  "#fdf1f4",
  "#fc8fb2",
  "#fa678e",
  "#ffa6c1",
  "#ffc4d6",
  "#ffe4e8",
  "#ff8db0",
  "#ff5e87",
  "#fc9fb5",
  "#fcb4c5",
  "#ffd2d8",
  "#fb859f",
  "#f94d78",
];