version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-development}  # Pass NODE_ENV as a build argument with a default value
    ports:
      - "8000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: ${NODE_ENV:-development}  # Set NODE_ENV for runtime
      TZ: Asia/Manila
